version: '3.3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - APP_NAME=DC
      - APP_ENV=development
      - APP_LANGUAGE=en
      - TZ=UTC
      - HTTP_ENABLE=true
      - HTTP_PORT=3001
      - PORT=3001
      - HTTP_HOST=0.0.0.0
      - HTTP_VERSIONING_ENABLE=true
      - HTTP_VERSION=1
      - DEBUGGER_HTTP_WRITE_INTO_FILE=false
      - DEBUGGER_HTTP_WRITE_INTO_CONSOLE=true
      - DEBUGGER_SYSTEM_WRITE_INTO_FILE=false
      - DEBUGGER_SYSTEM_WRITE_INTO_CONSOLE=true
    command: yarn start:dev
