export enum ENUM_DEADLINE_CALCULATOR_STATUS_CODE_ERROR {
  DEADLINE_CALCULATOR_NOT_FOUND_ERROR = 5200,
  DEADLINE_CALCULATOR_DEADLINE_CALCULATORNAME_EXISTS_ERROR = 5201,
  DEADLINE_CALCULATOR_EMAIL_EXIST_ERROR = 5202,
  DEADLINE_CALCULATOR_MOBILE_NUMBER_EXIST_ERROR = 5203,
  DEADLINE_CALCULATOR_IS_ACTIVE_ERROR = 5204,
  DEADLINE_CALCULATOR_INACTIVE_ERROR = 5205,
  DEADLINE_CALCULATOR_INACTIVE_PERMANENT_ERROR = 5206,
  DEADLINE_CALCULATOR_PASSWORD_NOT_MATCH_ERROR = 5207,
  DEADLINE_CALCULATOR_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 5208,
  DEADLINE_CALCULATOR_PASSWORD_EXPIRED_ERROR = 5209,
  DEADLINE_CALCULATOR_PASSWORD_ATTEMPT_MAX_ERROR = 5210,
  DEADLINE_CALCULATOR_BLOCKED_ERROR = 5211,
}

export enum ENUM_DEADLINE_CALCULATOR_STATUS_CODE_SUCCESS {
  DEADLINE_CALCULATOR_PASSWORD_EXPIRED_ERROR = 1000,
}
